#
#	Makefile for this SNAP example
#	- modify Makefile.ex when creating a new SNAP example
#
#	implements:
#		all (default), clean
#

include ../UtilsSNAP/Makefile.config
include Makefile.ex
include Makefile.exmain

#
# Makefile for non-Microsoft compilers
#
