#
#	Global configuration for SNAP makefiles
#

GLIB = glib-core
SNAP = snap-core
SNAPADV = snap-adv

CGLIB = UtilsSNAP/$(GLIB)
CSNAP = UtilsSNAP/$(SNAP)
CSNAPADV = UtilsSNAP/$(SNAPADV)




CC = g++
CXXFLAGS += -std=c++98 -Wall
CXXFLAGS += -O3 -DNDEBUG
# CXXFLAGS += -g3 -O0
# turn on for crash debugging, get symbols with <prog> 2>&1 | c++filt
#CXXFLAGS += -g -rdynamic
#CXXFLAGS += -ggdb
# turn on for OpenMP
CXXFLAGS += -fopenmp
LDFLAGS +=
LIBS += -lrt
